### ISSUE TITLE
Suggestion - Consistent Colour Coding Across Tabs

### ISSUE THREAD

**Issue by ljmacri** [AdliceSoftware/UCheck#10]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I checked that the feature I'm requesting is not available in UCheck Beta
- [X] I checked that the feature I'm requesting was not already requested

### Which feature do you want to be added ?

Now that installed and portable apps are listed on separate tabs in the UCheck BETA v5.0.6.0 interface please change the colour coding to avoid confusion for users.  Here is one suggestion for a slightly revised colour scheme:

### Installed Programs tab
- Keep the current royal blue background for Installed / Compatible programs
- Change the background for Installed / Community programs (currently grey) to **light / pale blue** (i.e., keeping an all-blue theme for Installed programs)
-  Keep Installed / Unsupported programs with no (white) background

### Portable Apps tab
-  Keep the current dark purple background for Portable / Compatible apps
-  Change the background for Portable / Community apps to **light / pale purple** (i.e., keeping an all-purple theme for Portable apps)
-  Keep Portable / Unsupported apps with no (white) background

### Consistent Colour Scheme on Updates Panel
When listing available updates on the Updates panel use the **same colour scheme** as the Installed and Portable tabs. For example, if there is an available update for a Installed / Community app on the Installed tab it should also have the same light / pale blue background on the Updates Panel.

I personally find the current colour scheme confusing.  For example, an Installed / Community program currently has a grey background on the Installed tab but this is changed to a dark navy blue background on the Updates panel if an update is available for that program.

### Red / Orange Text or Background Colour for Outdated Apps
If any Installed program or Portable app has a value of "Outdated" in the STATUS field then the text or background colour should be changed to **red if it is a major update** (e.g., from v7.x to v8.x) or **orange if a minor update** (e.g., from v7.0.x to v7.1.x) to improve the recognition of outdated programs.

### Sort Order on Installed Programs Tab

By default, installed programs should be sorted first by STATUS (i.e. with "Outdated" programs grouped at the top followed by "Latest" programs), and then sorted alphabetically (A to Z) by PROGRAM name within each group.

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Hi @ljmacri could you share a screenshot with your observations ?

**Comment by ljmacri** [comment]
Hi @Tigzy

For example, if I scan with UCheck v5.0.6.0 (stable) released 04-Dec-2023 it currently reports I have two Installed / Community programs (MS Edge and MS Office Home and Business 2019 C2R) where STATUS = "Outdated".

On the **Installed tab** these outdated Community programs have a **grey** background (*** see NOTE below) ...

![UCheck v5_0_6_0 Installed Tab Outdated MS Programs Have Grey Background 05 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/3ffbfa4b-8524-4c83-90ec-2e91848eb161)

... but when I switch to the **Updates tab** those same programs have a **dark blue** background.

![UCheck v5_0_6_0 Updates Tab Outdated MS Programs Have Dark Blue Background 05 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/72d02a4e-aad2-4677-b38e-e0bdd98b5cff)

It would be less confusing for users if colour coding for programs within the same category (e.g., Installed / Community) was consistent throughout the entire user interface.

Using an all-blue theme for Installed programs [royal blue (the current colour) for Compatible / light blue for Community] and an all-purple theme for Portable programs [dark purple (the current colour) for Compatible / light purple for Community] would also give user an immediate visual clue as to whether the update was for an Installed or Portable app when they switched to the Updates tab.
____________________________________

*** _NOTE: MS Edge v119.0.2151.97 is currently the latest stable release of this browser. The detection of a newer version is a bug in UCheck, which frequently recommends Insider Preview (beta) builds for many of my Microsoft programs_.

**Comment by Tigzy** [comment]
Thanks, it helps !

**Comment by Tigzy** [comment]
Implemented in 5.1
