### ISSUE TITLE
Product UCheck - False detection

### ISSUE THREAD

**Issue by mkvGuy** [AdliceSoftware/UCheck#11]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [ ] I am reporting an issue for UCheck BETA

### What happened?

MSEdge latest: 119 latest canary version 121
Waterfox latest G6.0.6 Reporting latest as 51.....

### ucheck-report

Program       : UCheck
Version       : 5.0.5.0
x64           : Yes
Program Date  : Nov 20 2023
Location      : C:\Program Files\UCheck\UCheck64.exe
Premium       : No
Company       : Adlice Software
Website       : https://www.adlice.com/
Contact       : https://adlice.com/contact/
Website       : https://adlice.com/download/ucheck/
Operating System : Windows 11 (10.0.22631) 64-bit
64-bit OS     : Yes
Startup       : 0
WindowsPE     : No
User          : Jamie
User is Admin : No
Date          : 2023/12/02 02:27:55
Type          : Scan
Aborted       : No
Scan Mode     : Standard
Updates Count : 2

************************* Warnings *************************

************************* Updates *************************
Waterfox (x64 en-US) (64-bit), version G6.0.6
  [+] Available Version        : 56.6
  [+] Size                     : 250 MB
  [+] Wow6432                  : No
  [+] Portable                 : No
  [+] update_location          : C:\Program Files\Waterfox

Microsoft Edge (32-bit), version 119.0.2151.97
  [+] Available Version        : 121.0.2248.1
  [+] Size                     : 97.5 MB
  [+] Wow6432                  : Yes
  [+] Portable                 : No

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [ ] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
I believe Waterfox was fixed yesterday. 
For Edge, it will be fixed once we fully support it. Leaving open for now.

**Comment by Tigzy** [comment]
Should be fixed
