### ISSUE TITLE
If an app is installed into a folder that is within a Custom Location, don't scan it and report version issues with it as if it were a portable app

### ISSUE THREAD

**Issue by stevehoek** [AdliceSoftware/UCheck#13]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [X] I am reporting an issue for UCheck BETA

### What happened?

I had Process Hacker installed as a portable app under my C:\BIN folder which is configured in Custom Locations
UCheck reported a version problem on a helper tool (peview.exe)
I then installed Process Hacker (setup) to that same folder
peview.exe is still being noted as out of date
If I install Process hacker in a default location (Program Files) it does not complain

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
I think we discussed this, you should not add custom locations containing installed programs. 
There's zero file difference between an installed program and a portable program, the only difference is an Uninstall registry entry, which may or man not contain the installation directory path. We cannot rely on registry data to tell whether a folder contains the installed or portable version of a program, and therefore cannot take decision on that; 
Only you know where you put your portable program files.
