### ISSUE TITLE
UCheck - False detection of Powershell

### ISSUE THREAD

**Issue by HayesE** [AdliceSoftware/UCheck#15]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [ ] I am reporting an issue for UCheck BETA

### What happened?

Powershell's latest version is their "release" version 7.4.0.0 dated 11/16/2023,
https://github.com/PowerShell/PowerShell/releases/tag/v7.4.0

UCheck incorrectly detects the release candidate 7.4.101 as newer, it is actually an older build; https://github.com/PowerShell/PowerShell/releases/tag/v7.4.0-rc.1

### ucheck-report

Program       : UCheck
Version       : 5.0.6.0
x64           : Yes
Program Date  : Dec  4 2023
Location      : C:\Program Files\UCheck\UCheck64.exe
Premium       : No
Company       : Adlice Software
Website       : https://www.adlice.com/
Contact       : https://adlice.com/contact/
Website       : https://adlice.com/download/ucheck/
Operating System : Windows 11 (10.0.22631) 64-bit
64-bit OS     : Yes
Startup       : 0
WindowsPE     : No
User          : [Nope]
User is Admin : No
Date          : 2023/12/09 18:22:52
Type          : Scan
Aborted       : No
Scan Mode     : Standard
Updates Count : 4

************************* Warnings *************************

************************* Updates *************************
PowerShell 7-x64 (64-bit), version 7.4.0.0
  [+] Available Version        : 7.4.101.0
  [+] Size                     : 267 MB
  [+] Wow6432                  : No
  [+] Portable                 : No

Microsoft Edge (32-bit), version 120.0.2210.61
  [+] Available Version        : 121.0.2256.2
  [+] Wow6432                  : Yes
  [+] Portable                 : No
  [+] update_location          : C:\Program Files (x86)\Microsoft\Edge\Application

PowerShell 7-x86 (32-bit), version 7.4.0.0
  [+] Available Version        : 7.4.101.0
  [+] Size                     : 250 MB
  [+] Wow6432                  : Yes
  [+] Portable                 : No

PCMark 10 (32-bit), version 2.1.2574.0
  [+] Available Version        : 2.1.2662.0
  [+] Size                     : 599 MB
  [+] Wow6432                  : Yes
  [+] Portable                 : No

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Powershell and EDGE will be soon integrated as Supported by UCheck

**Comment by Tigzy** [comment]
Should now be fixed.

**Comment by HayesE** [comment]
![PS](https://github.com/AdliceSoftware/UCheck/assets/121079365/b78d95e3-5f31-4990-aed3-892ef6df9fa2)
Still there.
