### ISSUE TITLE
Available Updates for Macrium Reflect Free v8.0.x Not Detected (Version Number Truncated)

### ISSUE THREAD

**Issue by ljmacri** [AdliceSoftware/UCheck#17]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [X] I am reporting an issue for UCheck BETA

### What happened?

I am currently using UCheck BETA v5.0.7.0 (rel. 05-Dec-2023) on a Win 10 Pro v22H2 laptop.

UCheck is unable to detect available updates for Macrium Reflect Free v8.0.x (Installed / Community) because the version number displayed in UCheck is **truncated to a single decimal place**. Please note that this problem was previously documented in my 02-Oct-2023 post # 251 in the Wilders Security forum topic at https://www.wilderssecurity.com/threads/ucheck-update-your-software-in-2-clicks.404593/page-11#post-3165403 when I was using an older version of UCheck BETA v4.11.0.0 .

For example, I currently have Macrium Reflect Free **v8.0.7690** (installed 13-Oct-2023).  An important **v8.0.7783 update was released on 01-Dec-2023** (see the release notes at https://updates.macrium.com/reflect/v8/v8.0.7783/details8.0.7783.htm) but UCheck will never detect this available update because it always reports that I have the latest available v8.0.

![UCheck BETA v5_0_7_0 Not Detecting Macrium Reflect Free v8_0 Updates 11 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/60062758-daa7-493b-a3c7-314942383faa)

Before it reached EOL on 31-Oct-2023, SUMo was able to correctly detect available updates for Macrium Reflect Free v8.0.x.  Here is a sample image captured on 13-Oct-2023.

![SUMo v5_17_10 Detecing Macrium Reflect Free v8_0_7690 13 Oct 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/97ba14ed-401a-4826-a7aa-66b8d901b091)
______________________________________

Like UCheck, Control Panel | Programs | Programs and Features only displays the version number of Macrium Reflect Free to a single decimal place.  However, File Explorer shows the full version number of various Macrium Reflect Free files (e.g., C:\Program Files\Macrium\Common\ReflectUI.exe, C:\Program Files\Macrium\Reflect\reflect.exe, etc.) when I view their file properties.

![Win 10 Pro v22H2 Control Panel Programs Macrium Reflect Free v8_0_7690 Truncated 11 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/de26e086-65c7-412f-a28f-14bee8e37442)

![Win 10 Pro v22H2 File Explorer Macrium Reflect Free reflect_exe v8_0_7690 11 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/f4155dfe-8e08-43e1-ab4c-616e3b1565f7)

### ucheck-report

I have attached a UCheck BETA v5.0.7.0 scan log and debug log for today's 11-Dec-2023 scan.

[UCheck BETA v5_0_7_0 Scan Log 11 Dec 2023.txt](https://github.com/AdliceSoftware/UCheck/files/13637435/UCheck.BETA.v5_0_7_0.Scan.Log.11.Dec.2023.txt)

[UCheck BETA v5_0_7_0 Debug Log 11 Dec 2023.txt](https://github.com/AdliceSoftware/UCheck/files/13637437/UCheck.BETA.v5_0_7_0.Debug.Log.11.Dec.2023.txt)

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
This is the same conclusion as here: https://github.com/AdliceSoftware/UCheck/issues/16
Unfortunately that's part of the community feedback limitations.
