### ISSUE TITLE
FR: Adding multiple folders at once for "Custom locations" -> Add folder

### ISSUE THREAD

**Issue by RonnyTNL** [AdliceSoftware/UCheck#18]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I checked that the feature I'm requesting is not available in UCheck Beta
- [X] I checked that the feature I'm requesting was not already requested

### Which feature do you want to be added ?

Current implementation for adding folders to custom locations only allows selecting one folder at a time.
For large portable implementations this would be more convenient if that could be made multi-select to add a bunch of folders in one go.

Part of this request comes from the fact that you can't easily "Exclude" certain folders but only product names, so if you have a large set of portable folders, but you wish to keep certain folders applications "private" then this becomes a bit of a puzzle.

### ucheck-report

N/A

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Unfortunately this isn't something supported by the UI library at the moment... 
So I guess the best is that you reorganize your directories internally to keep some part outside of the UCheck-monitored folders.
