### ISSUE TITLE
FR: Adding Exclusions BEFORE the results are send to the server.

### ISSUE THREAD

**Issue by RonnyTNL** [AdliceSoftware/UCheck#19]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I checked that the feature I'm requesting is not available in UCheck Beta
- [X] I checked that the feature I'm requesting was not already requested

### Which feature do you want to be added ?

In case a user want's to keep certain applications unknown to the cloud for whatever reason you first have to run a scan and then have to mark those as "Exclude" to prevent leaking their details.

From a privacy perspective it would be a more neat option to be able to exclude certain results before they are send to the cloud.

### ucheck-report

N/A

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
I don't think this is something that will be broadly used. 
As a workaround, you can disable Community feedback, then add the exclusions you want, and turn it back on.
