### ISSUE TITLE
FR: Portable Folder Exclusions and or more fine grained options for Exclusions in general.

### ISSUE THREAD

**Issue by RonnyTNL** [AdliceSoftware/UCheck#20]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I checked that the feature I'm requesting is not available in UCheck Beta
- [X] I checked that the feature I'm requesting was not already requested

### Which feature do you want to be added ?

Current implementation of Exclusions does not really fit the portable additions done lately.

In certain use-cases it would be very welcomed to be able to have more fine grained control over exclusions e.g. Folder based, Binary name (wildcard/regex).

### ucheck-report

N/A

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by RonnyTNL** [comment]
Example use-case;

I might want to just Exclude the UPX and/or UnRar detection for the portable app "Thor-lite" but not for all other portable folders that these tools might have been bundled with.

![image](https://github.com/AdliceSoftware/UCheck/assets/19427356/47885071-c5b3-4b03-a69e-cddbfa467263)

**Comment by RonnyTNL** [comment]
An other example of this "issue" 

![image](https://github.com/AdliceSoftware/UCheck/assets/19427356/968611ed-a9fb-4289-965c-f8de9617046a)

**Comment by Tigzy** [comment]
That's a good point, we'll see if we can add a new action item based on path (whether it's the parent folder or the item itself)

**Comment by Tigzy** [comment]
Implemented in 5.1
