### ISSUE TITLE
FR: add "Skip this update" to Installed -> Portable tab context-menu. (Preferably with ignore for 7, 14 or 30 days).

### ISSUE THREAD

**Issue by RonnyTNL** [AdliceSoftware/UCheck#21]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I checked that the feature I'm requesting is not available in UCheck Beta
- [X] I checked that the feature I'm requesting was not already requested

### Which feature do you want to be added ?

In case you run in to a portable "update" that happens to be a beta/nightly it would be nice to be able to mark that as "Skip this update" and or implement a new "Ignore for x days" option. 

in SUMO terms there was even an option to Ignore for x days e.g. 7, 14, 30 so that once the beta release was over and it happens to release on the same build number you would still get a notification later on.

### ucheck-report

N/A

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Good idea, thanks.

**Comment by Tigzy** [comment]
fixed.
