### ISSUE TITLE
FR: Check a subset of the portable detections for "update" after you think you fixed the outdated detection

### ISSUE THREAD

**Issue by RonnyTNL** [AdliceSoftware/UCheck#22]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I checked that the feature I'm requesting is not available in UCheck Beta
- [X] I checked that the feature I'm requesting was not already requested

### Which feature do you want to be added ?

On SUMO you could select an outdated detection and do a "Check" independent of all other results in the list.
This was useful to check if your attempt to update the outdated detection worked, and via this way you could "clean-up" our outdated detections without having to do full-scan's in between.

This will drastically reduce the load on the cloud infrastructure as well as it's just a small JSON call instead of the full set.

### ucheck-report

N/A

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Hi, this is actually already done after an update. 
If the item becomes red, it means the update failed (no version change). Green = success.
