### ISSUE TITLE
32 bit Chrome Canary is detected as 64 bit version 

### ISSUE THREAD

**Issue by RonnyTNL** [AdliceSoftware/UCheck#24]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [X] I am reporting an issue for UCheck BETA

### What happened?

UCheck 5.0.7.0

![image](https://github.com/AdliceSoftware/UCheck/assets/19427356/31faad7a-c969-403f-a499-44a300f68347)

![image](https://github.com/AdliceSoftware/UCheck/assets/19427356/a6c0c21f-ac0d-4dd6-9a2c-ad0043517f72)

![image](https://github.com/AdliceSoftware/UCheck/assets/19427356/33a60aad-03e9-41f7-93b8-f16cfa3f95f5)

### ucheck-report

2023/12/15 11:47:02:DEBUG	[UCheck::CreateCommunityUpdatesList] Found outdated program: Google Chrome Canary (122.0.6183.0 => 122.0.6185.0)

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Well, and I believe that the 64-bit version is detected as 32-bit (some other user reported). 
Since we only have this issue with Chrome, to me it's a no-fix. Google needs to fix their installer...
