### ISSUE TITLE
A newer portable version on the machine is shown as "outdated" I guess that should not be tagged as "outdated"

### ISSUE THREAD

**Issue by RonnyTNL** [AdliceSoftware/UCheck#25]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [X] I am reporting an issue for UCheck BETA

### What happened?

5.0.7.0 Beta2
Newer version shown as outdated.

![image](https://github.com/AdliceSoftware/UCheck/assets/19427356/6cd38fd6-be4d-4b99-b9ef-28b6d66b8f22)

### ucheck-report

2023/12/17 12:17:23:DEBUG	[UCheck::CreateCommunityUpdatesList] Found outdated program: Sysinternals Contig (1.8.3.0 => 1.70.0.0)

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Should be fixed with 5.1

**Comment by RonnyTNL** [comment]
Seems it's still there; stable 5.1

Looks like .70 is seen as a higher version then .8 or .53 higher as .6
On itself that would be logic, but in the complete versioning scheme they use 1.8 is newer then 1.70 / 3.6 newer then 3.53

![image](https://github.com/AdliceSoftware/UCheck/assets/19427356/6c41f6fe-a0dc-45f3-a150-e732cf367fe8)

**Comment by jascoet-mwb** [comment]
Well isn't 70 higher than 8 ? :) 
It looks valid to me, that's just a wrong versioning from SysInternal

**Comment by Tigzy** [comment]
Well isn't 70 higher than 8 ? :)
It looks valid to me, that's just a wrong versioning from SysInternal
They should have put version 1.7.0.0 / 3.5.3.0 instead.

**Comment by RonnyTNL** [comment]
Yes that's what I wrote ;)

I guess their will be more applications having weird versioning scheme's e.g. LibreWolf not quite sure how SUMO handled that 
Perhaps because he also had a solution for "report beta" e.g. if a newer version was shown as stable, maybe he could override that in the database or something, but that would mean manual labor I guess. In this case you would probably need to remove the 1.70.0.0 entry and set 1.8.3.0 as latest.

![image](https://github.com/AdliceSoftware/UCheck/assets/19427356/c406e249-2604-40da-8009-12704e51f3b8)

**Comment by Tigzy** [comment]
Sorry, yeah I just understood the issue you described because a similar issue have been fixed. 
To me it's impossible to know the intent without introducing defects for other apps. 

For example, how do you know if 3.11.0 means 3.11 or 3.1.1 ?

**Comment by RonnyTNL** [comment]
I understand that there is no regex to fix this, that's why I suspect this was manual labor on the SUMO solution.

Perhaps a "report incorrect version" similar to "report beta version" which would flag the entry in the database, the more reports there are the more likely it is that there is something wrong with it. Though that would probably still need a manual fix in the database.
