### ISSUE TITLE
Apps that release yearly (TurboTax, AutoCAD, Visual Studio) get detected as outdated when latest edition is updated

### ISSUE THREAD

**Issue by stevehoek** [AdliceSoftware/UCheck#26]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [ ] I am reporting an issue for UCheck BETA

### What happened?

I have three apps, TurboTax, AutoCAD, and Visual Studio, that release yearly, like TurboTax 2021, TurboTax 2022, AutoCAD 2023, AutoCAD 2024
The apps are installed independently, with independent registry install entries, etc.

When TurboTax 2023 has an update, like today for instance, UCheck falsely claims that TurboTax 2021 and TurboTax 2022 are now out of date.

Please treat apps like these as their own entities and track their versions independently from one another.  SUMo did well with this.

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Fixed server side, it should self heal little by little. Please re-open if you still have the issue in a couple weeks from now.
