### ISSUE TITLE
Confusing "End trial" prompt in UCheck.

### ISSUE THREAD

**Issue by Regmos** [AdliceSoftware/UCheck#27]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [X] I am reporting an issue for UCheck BETA

### What happened?

When updating the "common_lang_da.ts" I stumbled upon this.
When clicking "End trial", you get this prompt. It's a bit confusing.

![UCheck_end_trial](https://github.com/AdliceSoftware/UCheck/assets/811857/a8edbaa4-0223-42b9-8851-00886a4e2fcb)

In the language file you have these two strings.

![Common_lang_ts](https://github.com/AdliceSoftware/UCheck/assets/811857/b6dd1422-461c-4887-8eb1-7dadca4b42ad)

Isn't number 1 more appropriate ?

Kind regards 
Regmos

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [x] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Yes, that's a bug. Thanks for finding it

**Comment by Tigzy** [comment]
Fixed in latest version
