### ISSUE TITLE
UCheck Classifies BleachBit Portable as "Unsupported" Instead of "Community"

### ISSUE THREAD

**Issue by ljmacri** [AdliceSoftware/UCheck#28]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [X] I am reporting an issue for UCheck BETA

### What happened?

UCheck BETA-1 v5.2.0.0 (rel. 22-Dec-2023) does not check for available updates for my BleachBit for Windows Portable v4.x app. The "Company" name of the bleachbit.exe and bleachbit_console.exe executables are missing in the UCheck interface but I am unsure why this file property is required in order to perform a version check when the Product Name, File Name and File Version are all known. 

Here is the output when I use Sysinternal's Sigcheck v4.90 (available at https://learn.microsoft.com/en-us/sysinternals/downloads/sigcheck) to check the properties of the portable version of bleachbit.exe that confirms that "Company" is unknown.

[Sigcheck64 v2_90 Output for BleachBit_exe Portable v4_6_0 24 Dec 2023.txt](https://github.com/AdliceSoftware/UCheck/files/13762991/Sigcheck64.v2_90.Output.for.BleachBit_exe.Portable.v4_6_0.24.Dec.2023.txt)
__________________________________________

I am using the latest BleachBit for Windows Portable v4.6.0 (available at https://www.bleachbit.org/download/windows) and have unzipped the BleachBit-4.6.0-portable.zip file on a removable USB stick at E:\Portable\BleachBit 4_6_0.

I have ~30 portable apps on this USB stick and UCheck classifies almost every portable app as Community Only / Portable.  However BleachBit Portable v4.6.0 (along with WhyNotWin11 Portable v2.5.0.5 from https://github.com/rcmaehl/WhyNotWin11) is classified as **Unsupported** / Portable and UCheck does not look up the latest available version for BleachBit Portable.

The Portable tab of UCheck shows the "**Company**" name for the main **bleachbit.exe** executable is **missing** ...

![UCheck BETA-1 v5_2_0_0 Portable BleachBti WhyNotWin11 Unsupported Part A 23 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/d69d0d48-aa74-4c8e-a619-347361fb7106)

![UCheck BETA-1 v5_2_0_0 Portable BleachBti WhyNotWin11 No Company Part B 23 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/97c60b08-28df-4ef5-94b1-d23df054367e)

... but the file properties of bleachbit.exe appear to include necessary details like Product Name, Product Version, etc. I am not sure if it is relevant, but the digital certificate of this file was only valid to 23-Nov-2023.

![Win 10 Pro v22H2 File Explorer Portable BleachBit_exe Properties 23 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/bfaaf771-d93b-438d-b810-eba805f66a31)

![Win 10 Pro v22H2 File Explorer Portable BleachBit_exe Digital Signature 24 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/8ed5e5aa-59f1-4dcb-91a5-463cb068ae53)

Also note that there are three "helper" executables (**fc-cache.exe, gspawn-win32-helper.exe and gspawn-win32-helper-console.exe**) bundled with BleachBit Portable that are missing details like Product Name, Product Version and are filtered out as "uninteresting" in the UCheck debug log.

![Win 10 Pro v22H2 File Explorer Portable BleachBit fc_cache_exe Properties 23 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/6abe90af-5569-42b0-93f3-80eea29db296)

### ucheck-report

The attached .TXT files are my UCheck scan log from 24-Dec-2023 and an excerpt of the debug log at C:\ProgramData\UCheck\Debug\UCheck_debug.log for that 24-Dec-2023 scan.

[UCheck BETA-1 v5_2_0_0 Scan Log 24 Dec 2023.txt](https://github.com/AdliceSoftware/UCheck/files/13762321/UCheck.BETA-1.v5_2_0_0.Scan.Log.24.Dec.2023.txt)
[UCheck BETA-1 v5_2_0_0 Debug Log 24 Dec 2023.txt](https://github.com/AdliceSoftware/UCheck/files/13762323/UCheck.BETA-1.v5_2_0_0.Debug.Log.24.Dec.2023.txt)

Here's are excerpts from the scan log and debug log where there is a match for "bleachbit":

From the **scan log**:

BleachBit - Free space and maintain privacy (32 bits), version 4.6.0.0
  [+] Location            : E:\Portable\BleachBit 4_6_0\bleachbit.exe

BleachBit - Free space and maintain privacy (32 bits), version 4.6.0.0
  [+] Location            : E:\Portable\BleachBit 4_6_0\bleachbit_console.exe

From the **debug log**:

2023/12/24 08:29:13:DEBUG	[UCheck::SearchWellKnownLocation] Found app: E:\Portable\BleachBit 4_6_0\bleachbit.exe
2023/12/24 08:29:14:DEBUG	[UCheck::SearchWellKnownLocation] Found app: E:\Portable\BleachBit 4_6_0\bleachbit_console.exe
2023/12/24 08:29:14:DEBUG	[UCheck::SearchWellKnownLocation] Found app: E:\Portable\BleachBit 4_6_0\fc-cache.exe
2023/12/24 08:29:14:DEBUG	[UCheck::ShouldFilter] No program name: E:\Portable\BleachBit 4_6_0\fc-cache.exe
2023/12/24 08:29:14:DEBUG	[UCheck::SearchWellKnownLocation] App is uninteresting, filtering: E:\Portable\BleachBit 4_6_0\fc-cache.exe
2023/12/24 08:29:14:DEBUG	[UCheck::SearchWellKnownLocation] Found app: E:\Portable\BleachBit 4_6_0\gspawn-win32-helper.exe
2023/12/24 08:29:14:DEBUG	[UCheck::ShouldFilter] No program name: E:\Portable\BleachBit 4_6_0\gspawn-win32-helper.exe
2023/12/24 08:29:15:DEBUG	[UCheck::SearchWellKnownLocation] App is uninteresting, filtering: E:\Portable\BleachBit 4_6_0\gspawn-win32-helper.exe
2023/12/24 08:29:15:DEBUG	[UCheck::SearchWellKnownLocation] Found app: E:\Portable\BleachBit 4_6_0\gspawn-win32-helper-console.exe
2023/12/24 08:29:15:DEBUG	[UCheck::ShouldFilter] No program name: E:\Portable\BleachBit 4_6_0\gspawn-win32-helper-console.exe
2023/12/24 08:29:15:DEBUG	[UCheck::SearchWellKnownLocation] App is uninteresting, filtering: E:\Portable\BleachBit 4_6_0\gspawn-win32-helper-console.exe

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Yes, unfortunately programs having no Company Name / Program Name / Version Info cannot be classified, and therefore won't have community update. That's something only them can fix by putting proper version info...
