### ISSUE TITLE
UCheck identifies new version of Free Download Manager but downloads and installs latest publicly available version that is already installed

### ISSUE THREAD

**Issue by stevehoek** [AdliceSoftware/UCheck#29]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [ ] I am reporting an issue for UCheck BETA

### What happened?

Free Download Manager (FDM) v6.20.0.5510 is installed and is also the latest publicly available version on freedownloadmanager.org website.  UCheck has offered new version .5514 and today .5524 but when installing from UCheck the same .5510 version is downloaded and installed.  This is not a community app.

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
This is because FDM released 6.20.0.5524 only for Android it seems, but it's not specified anywhere in the version history page.
https://www.videohelp.com/software/Free-Download-Manager-/version-history
We'll see if we can find a better data.

**Comment by Tigzy** [comment]
Should now be fixed.
