### ISSUE TITLE
wrong link for update

### ISSUE THREAD

**Issue by BillH99999** [AdliceSoftware/UCheck#30]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [ ] I am reporting an issue for UCheck BETA

### What happened?

Today I was offered an update to CPUID HWMonitor.

On the update tab the company name is shown as "Zoom Video Communications".
The update is for updating version 1.52 to version 5.17.28914.

![image](https://github.com/AdliceSoftware/UCheck/assets/26846819/afaeba17-7219-4d34-921b-26db9d6c5cb4)

When I click on "Open Website", it takes me to https://zoom.us/support/download and starts a download of Zoom, not CPUID HWMonitor.

Something is wrong here.

If I go to https://www.cpuid.com/softwares/hwmonitor.html (the home of CPUID HWMonitor), it shows the current version is still 1.52.

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [x] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Are you able to reproduce this issue ? 
It looks like a UI cross reference, but I cannot reproduce it.

**Comment by Tigzy** [comment]
Closed for now, until repro.

**Comment by BillH99999** [comment]
@Tigzy,

It no longer shows as an update for me and all looks well.

Bill
