### ISSUE TITLE
Improve handling of betas in community database

### ISSUE THREAD

**Issue by G-N-ius** [AdliceSoftware/UCheck#31]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I checked that the feature I'm requesting is not available in UCheck Beta
- [X] I checked that the feature I'm requesting was not already requested

### Which feature do you want to be added ?

Currently, the check against the community database reports many "new versions" which are actually still in beta.
This is obviously because there is some Ucheck user somewhere that has this beta installed and updated the community DB with this version.
I assume that most users are not interested in Beta versions.

### Proposal for improvement:
- add a Beta-flag in the DB (allow entries with and without the flag being set)
- add a checkbox (e.g. "I use Betas") in the community options of the Ucheck-UI
- when checking, exclude versions flagged as beta, unless user has the Beta-checkbox ticked
- when uploading from a Beta user, add **new** DB entries for this version with the Beta flag being set (no need to touch existing entries)

I'm sure this will already improve the situation a lot, even though it won't get to 100%

Additionally, GUI options to send notifications about false Beta/non-Beta marks might help
(do I need to mention that I'm a former SUMo user ?)

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
The problem with this "flag" is that it would be a manual action, requiring us to go through all the database to add those flags. 
And remove them when they not longer are betas. 
I'm not sure this is the way to go, but I'm open to a more feasible solution.

**Comment by G-N-ius** [comment]
Well, the proposal was actually meant to be an automatic process.
The only manual interaction would be on client side, where the users would check/uncheck their "I use Betas" flag.

If Beta users upload new versions, these should preliminary be considered Betas and marked accordingly in the DB.
While those new versions reported by non-Beta users should be marked as stable versions (overruling same or older Beta versions).

I'm aware that this will not give a 100% correct Beta-status, but it will prevent many update reports for Betas for those that are only interested in stable versions. For the price of a possible slight delay in reporting, in the case that the first uploaded version is from a Beta user.

**Comment by Tigzy** [comment]
"If Beta users upload new versions, these should preliminary be considered Betas and marked accordingly in the DB.
While those new versions reported by non-Beta users should be marked as stable versions (overruling same or older Beta versions)."

This would not work, because vast majorité of people would not turn this flag on, we would still get BETA versions in the db. 
Also that would also incorrectly flag non-beta as beta with no distinction. 

I think we can close this ticket, we have implemented a server side mechanism to manually flag beta / errornous version number on our side. I think we'll live with that for now.
