### ISSUE TITLE
Volume2 false update

### ISSUE THREAD

**Issue by BillH99999** [AdliceSoftware/UCheck#32]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [ ] I am reporting an issue for UCheck BETA

### What happened?

Today I was offered an update for Volume2 from version1.1.8 to 1.1.8.465.

![image2](https://github.com/AdliceSoftware/UCheck/assets/26846819/1bb85ae2-5dfa-46e4-b764-5a8fc769a308)

I am already on 1.1.8.465 and have been since last year.

![image1](https://github.com/AdliceSoftware/UCheck/assets/26846819/315501e3-9e11-4ee7-b4d4-68adbec862ea)

Also why does the Updates tab show that 1.1.8.465 was from 27 January 2024 when it was actually released on 16 September 2023?

Bill

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [ ] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by BillH99999** [comment]
Now it is showing an update to version from 1.1.8 to 1.1.9 which incorrect.  The Volume2 website still shows 1.1.8.465 is the latest version.

Bill

**Comment by Tigzy** [comment]
Hi, I don't know what the official website for Volume2 is, but here it says the latest is 1.1.9.466
https://volume2.en.lo4d.com/windows
This information comes from our users, so it looks like a lot of them have this version...

**Comment by Tigzy** [comment]
For now closing because the version cut off is the classic "Generic code" issue, Volume2 is a Community software and thus relies on non-perfect rules to find the version number...
