### ISSUE TITLE
Installed Apps identified as 32bit when they are actually the 64bit versions

### ISSUE THREAD

**Issue by jrp2706** [AdliceSoftware/UCheck#33]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [ ] I am reporting an issue for UCheck BETA

### What happened?

I have just installed UCheck version 5.2.2 to see if it is a suitable replacement for SUMo and after running a Scan I have noticed that two of my installed applications (Tribler & CyberDuck ) have been reported as being the 32bit versions when they are in fact the 64bit versions. They have been detected correctly as being in C:\Program Files rather than C:\Program Files (x86) which is where they would have been if they were the 32bit versions.

### ucheck-report

2024/02/01 15:47:24:DEBUG	[RKCore::Clean] Freeing resources...
2024/02/01 15:47:24:DEBUG	[Workers::Stop] Stopping worker (AdvertNotifs)...
2024/02/01 15:47:24:DEBUG	[Workers::Stop] Stopping worker (Agent)...
2024/02/01 15:47:24:DEBUG	[Workers::Stop] Stopping worker (Scheduler)...
2024/02/01 15:47:24:DEBUG	[Workers::Stop] Stopping worker (ScannerWorker)...
2024/02/01 15:47:24:DEBUG	[CoreScanner::UnregisterSignals] Removing callbacks...
2024/02/01 15:47:24:DEBUG	[Workers::Stop] Stopping worker (ScannerWorker)...
2024/02/01 15:47:24:DEBUG	[CoreScanner::UnregisterSignals] Removing callbacks...
2024/02/01 15:47:24:DEBUG	[Workers::Stop] Stopping worker (ScannerWorker)...
2024/02/01 15:47:24:INFO	[QuarantineEngine::Release] Releasing quarantine items...
2024/02/01 15:47:25:INFO	[Cloud::SerializeCache] Saving cache in C:\ProgramData\UCheck\cloud.cache (0 entries)...
2024/02/01 15:47:25:INFO	[VTScanner::SerializeCache] Saving cache in C:\ProgramData\UCheck\vt.cache (0 entries)...
2024/02/01 15:48:10:INFO	[InstallManager::Install] Installing (C:\ProgramData\UCheck)...
2024/02/01 15:48:10:DEBUG	[RKCore::InitImpl] Initializing UCheck:5.2.2.0
2024/02/01 15:48:10:DEBUG	[RKCore::Init] Initializing UCheck:5.2.2.0
2024/02/01 15:48:10:DEBUG	[Licensing::CheckLicense] No license found, missing info
2024/02/01 15:48:10:INFO	[VersionManager::Software::CheckIfOutdated] Software up to date (5.2.2.0)
2024/02/01 15:48:10:INFO	[DynamicConfig::Refresh] Read config with success, malpe::rtp_enforce=1, malpe::rtp_silent=0
2024/02/01 15:48:10:DEBUG	[ReportEngine::SetPath] Path set (C:\ProgramData\UCheck\reports)
2024/02/01 15:48:10:DEBUG	[ReportEngine::Unserialize] Unserializing, found 4 reports.
2024/02/01 15:48:10:DEBUG	[SchedulerCommon::Load] Loading tasks...
2024/02/01 15:48:10:DEBUG	[SchedulerCommon::CreateTask] Creating task (scan)
2024/02/01 15:48:10:DEBUG	[SchedulerCommon::CreateTask] Creating task (update_check)
2024/02/01 15:48:10:DEBUG	[SchedulerCommon::CreateTask] Creating task (scan_reminder)
2024/02/01 15:48:10:DEBUG	[SchedulerCommon::CreateTask] Creating task (marketing)
2024/02/01 15:48:10:DEBUG	[SchedulerCommon::CreateTask] Creating task (review)
2024/02/01 15:48:10:DEBUG	[SchedulerCommon::CreateTask] Creating task (rtp)
2024/02/01 15:48:10:DEBUG	[ITask] Added TaskScan:scan::8F364ECD [interval: 0/0] [start: 9/0] [run: 0/-1] [last run: 1601/01/01 00:00:00] [last set: 2024/02/01 13:59:23] [next run:  00:00:00]
2024/02/01 15:48:10:DEBUG	[ITask] Added TaskUpdateCheck:update_check::09C84BAF [interval: 3/1] [start: 2/10] [run: 2/-1] [last run: 2024/02/01 15:09:24] [last set: 2024/02/01 13:59:23] [next run: 2024/02/01 16:09:24]
2024/02/01 15:48:10:DEBUG	[ITask] Added TaskScanReminder:scan_reminder::EA10FE09 [interval: 4/1] [start: 2/30] [run: 1/-1] [last run: 2024/02/01 14:29:23] [last set: 2024/02/01 13:59:23] [next run: 2024/02/02 14:29:23]
2024/02/01 15:48:10:DEBUG	[ITask] Added TaskMarketing:marketing::C9B4A91D [interval: 4/1] [start: 3/6] [run: 0/-1] [last run: 1601/01/01 00:00:00] [last set: 2024/02/01 13:59:23] [next run: 2024/02/01 19:59:23]
2024/02/01 15:48:10:DEBUG	[ITask] Added TaskReview:review::1D0FAAB2 [interval: 4/7] [start: 4/1] [run: 0/-1] [last run: 1601/01/01 00:00:00] [last set: 2024/02/01 13:59:23] [next run: 2024/02/02 13:59:23]
2024/02/01 15:48:10:DEBUG	[ITask] Added TaskRTP [interval: 2/60] [start: 9/-1] [run: 2/-1] [last run: 2024/02/01 14:59:25] [last set: 2024/02/01 13:59:23] [next run: 2024/02/01 15:59:25]
2024/02/01 15:48:10:DEBUG	[Workers::Register] Registering worker (Scheduler)...
2024/02/01 15:48:10:DEBUG	[Workers::Register] Registering worker (Agent)...
2024/02/01 15:48:10:DEBUG	[Workers::Start] Starting worker (Agent)...
2024/02/01 15:48:10:DEBUG	[Workers::Start] Starting worker (Scheduler)...
2024/02/01 15:48:10:INFO	[InstallManager::RegisterAtStartup] Registration, startup=0, name=UCheck, path=G:\My Downloads\UCheck_portable64_5.2.2.exe, svc=, admin=1
2024/02/01 15:48:10:INFO	[InstallManager::RegisterAtStartup] Removing all startup entries, name=UCheck
2024/02/01 15:48:10:DEBUG	[ReportFactory::RegisterType] Registered type UCHECK-REPORT
2024/02/01 15:48:10:DEBUG	[ReportEngine::Unserialize] Unserializing, found 4 reports.
2024/02/01 15:48:10:DEBUG	[ITask] Added TaskScan [interval: 0/0] [start: 2/1] [run: 0/-1] [last run: 2024/02/01 15:26:49] [last set: 2024/02/01 15:48:10] [next run:  00:00:00]
2024/02/01 15:48:10:DEBUG	[ITask] Added TaskCacheCleanup [interval: 0/0] [start: 2/5] [run: 0/-1] [last run: 1601/01/01 00:00:00] [last set: 2024/02/01 15:48:10] [next run:  00:00:00]
2024/02/01 15:48:10:DEBUG	[Advert::Unserialize] Loading campaigns...
2024/02/01 15:48:10:DEBUG	[ITask] Added TaskAdvert:12 [campaign: Save 20% with our special Bundle !] [interval: 3/5] [start: 2/5] [run: 1/2] [last run: 2024/02/01 14:04:25] [last set: 2024/02/01 15:48:10] [next run: 2024/02/01 19:04:25]
2024/02/01 15:48:10:DEBUG	[Advert::Serialize] Saving campaigns...
2024/02/01 15:48:10:DEBUG	[Workers::Register] Registering worker (AdvertNotifs)...
2024/02/01 15:48:11:INFO	[VersionManager::Software::CheckIfOutdated] Software up to date (5.2.2.0)
2024/02/01 15:48:12:INFO	[SDKConfig::MigrateOldConfig] Attempting to migrate old config...
2024/02/01 15:48:12:INFO	[SDKConfig::MigrateOldConfig] Attempting to migrate old config...
2024/02/01 15:48:12:INFO	[SDKConfig::MigrateOldConfig] Attempting to migrate old config...
2024/02/01 15:49:00:DEBUG	[ReportEngine::DeleteReport] Removed report (133512748080000000).
2024/02/01 15:49:00:DEBUG	[ReportEngine::DeleteReport] Removed report (133512700400000000).
2024/02/01 15:49:41:INFO	[VTScanner::UnSerializeCache] Loading cache...
2024/02/01 15:49:41:INFO	[VTScanner::UnSerializeCache] 0 entries loaded
2024/02/01 15:49:41:INFO	[Cloud::UnSerializeCache] Loading cache...
2024/02/01 15:49:41:INFO	[Cloud::UnSerializeCache] 0 entries loaded
2024/02/01 15:49:41:INFO	[QuarantineEngine::Init] Loading quarantine engine...
2024/02/01 15:49:41:INFO	[QuarantineEngine::SetQuarantineFolder] Loading quarantine items from (C:\ProgramData\UCheck\quarantine)
2024/02/01 15:49:41:INFO	[QuarantineEngine::Release] Releasing quarantine items...
2024/02/01 15:49:41:INFO	[QuarantineEngine::SetQuarantineFolder] Loaded 0 items.
2024/02/01 15:49:41:INFO	[Exclusions::Unserialize] Loading exclusions...
2024/02/01 15:49:41:INFO	[RulesEngine::LoadRules] Loading rules...
2024/02/01 15:49:41:INFO	[RulesEngine::ReadRulesFromResources] Loading rules from resources...
2024/02/01 15:49:41:CRITICAL	[RulesEngine::ReadRulesFromResources] Unable to find rules
2024/02/01 15:49:41:INFO	[Exclusions::Serialize] Saving exclusions...
2024/02/01 15:49:41:DEBUG	[ReportFactory::RegisterType] Registered type RK-REPORT
2024/02/01 15:49:41:DEBUG	[ReportEngine::Unserialize] Unserializing, found 0 reports.
2024/02/01 15:49:41:DEBUG	[CoreScanner::RegisterWorkers] Registering & starting workers...
2024/02/01 15:49:41:DEBUG	[Workers::Register] Registering worker (ScannerWorker)...
2024/02/01 15:49:41:DEBUG	[Workers::Start] Starting worker (ScannerWorker)...
2024/02/01 15:49:41:DEBUG	[CoreScanner::RegisterSignals] Registering callbacks...
2024/02/01 15:49:41:DEBUG	[CloudScanWorker::Reset] Cloud status=OK, limited=0
2024/02/01 15:49:41:INFO	[DynamicConfig::Refresh] Read config with success, malpe::rtp_enforce=1, malpe::rtp_silent=0
2024/02/01 15:49:41:DEBUG	[UCheck::GetUpdateable] Getting updateable programs...
2024/02/01 15:49:41:DEBUG	[UCheck::GetUpdateable] Found 248 updateable programs.
2024/02/01 15:49:41:DEBUG	[UCheck::CreateInstalledList] Searching installed programs...
2024/02/01 15:49:41:DEBUG	[UCheck::FetchProgramKey] Version is empty, using file version for program name: EaseUS Data Recovery Wizard, 16.3.0.0
2024/02/01 15:49:42:DEBUG	[UCheck::FetchProgramKey] Version is empty, using file version for program name: WhySoSlow 1.61, 1.61.0.0
2024/02/01 15:49:42:DEBUG	[UCheck::FetchProgramKey] Version is empty, using file version for program name: MEGAsync, 4.12.2.0
2024/02/01 15:49:42:DEBUG	[UCheck::FetchProgramKey] Version is empty, using file version for program name: Tixati, 3.19.1.0
2024/02/01 15:49:43:DEBUG	[UCheck::CreateInstalledList] Found 189 installed programs, total size 22658703360.
2024/02/01 15:49:43:DEBUG	[UCheck::CreateUpdatesList] Searching updates...
2024/02/01 15:49:43:DEBUG	[UCheck::CreateUpdatesList] Found outdated program: AviSynth (2.6.0 MT => 3.7.3)
2024/02/01 15:49:43:DEBUG	[UCheck::CreateUpdatesList] Found outdated program: Tribler (7.12.1 => 7.13.1)
2024/02/01 15:49:43:DEBUG	[UCheck::CreateUpdatesList] Found outdated program: Cyberduck (8.7.2.40975 => 8.7.3.40979)
2024/02/01 15:49:44:DEBUG	[UCheck::CreateAvailableList] Getting available programs (API)...
2024/02/01 15:49:45:WARNING	[UCheck::GetDownloadLinkToInstall] Program Adobe Acrobat Reader has no downloable link.
2024/02/01 15:49:46:INFO	[Telemetry::Send] Sending telemetry data
2024/02/01 15:49:46:DEBUG	[ReportFactory::RegisterType] Creating report of type UCHECK-REPORT
2024/02/01 15:49:46:DEBUG	[ReportEngine::AddNewReport] Creating new report (AdliceReport_UCHECK-REPORT_02012024_154945.json)...
2024/02/01 15:49:46:DEBUG	[Scheduler::Reload] Reloading all tasks...

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [ ] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Hi,
I fear this is a bug on their own as they were installed into the "Wow6432" node of the registry, which is reserved for 32-bit. 
We'll add a second-chance attempt to read if the main binary location exists and is 64-bit, but if that data isn't present I'm afraid it's the only way for us to guess the bitness.

**Comment by Tigzy** [comment]
Should be fixed in latest version
