### ISSUE TITLE
UCheck is still using a SHA1 certificate which is generally considered weak

### ISSUE THREAD

**Issue by jrp2706** [AdliceSoftware/UCheck#34]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [ ] I am reporting an issue for UCheck BETA

### What happened?

I am trying UCheck for the first time and have noticed that the portable .exe file is only signed with a SHA1 certificate. This is considered as no longer secure and it is recommended to at least use a SHA2 (SHA256 or SHA512) one instead
See https://en.wikipedia.org/wiki/Secure_Hash_Algorithms for further details.

### ucheck-report

![image](https://github.com/AdliceSoftware/UCheck/assets/91820135/5d72d201-311e-48d9-91f3-6c1d715396b7)
![image](https://github.com/AdliceSoftware/UCheck/assets/91820135/1447cfe6-1f6b-41d0-8f24-02ada60ead86)

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [ ] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Hi,
This is intentional because we still support older operating systems like Windows 7. 
Those barely support SHA1 (with some KB patch) and won't support SHA2xx. 
Closing as won't do, this will evolve whenever we decide to drop Windows 7 support.

**Comment by jrp2706** [comment]
Ok, thanks for the explanation.

Cheers
