### ISSUE TITLE
Foxit PDF Editor Version 2023 vs 13

### ISSUE THREAD

**Issue by 00Eraser00** [AdliceSoftware/UCheck#36]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I checked that the feature I'm requesting is not available in UCheck Beta
- [X] I checked that the feature I'm requesting was not already requested

### Which feature do you want to be added ?

Foxit PDF Editor has two types of licenses that differ in their version number ⇾ [https://www.foxit.com/downloads/](https://www.foxit.com/downloads/) They are essentially the same software except for a couple features, but the subscription license has version 2023.x.x.xxxxx and the perpetual license has version 13.x.x.xxxxx. Is it possible for you to distinguish between those two? Because version 2023 is not really an update of version 13. Unfortunately, those two are installed in the same path under the same name, similar to Microsoft Office 365 and Microsoft Office 2021.

### ucheck-report

Program       : UCheck
Version       : 5.2.2.0
x64           : Yes
Program Date  : Jan  9 2024
Location      : C:\Program Files\UCheck\UCheck64.exe
Premium       : No
Company       : Adlice Software
Website       : https://www.adlice.com/
Contact       : https://adlice.com/contact/
Website       : https://adlice.com/download/ucheck/
Operating System : Windows 10 (10.0.19045) 64-bit
64-bit OS     : Yes
Startup       : 0
WindowsPE     : No
User          : Jan
User is Admin : No
Date          : 2024/02/04 11:46:50
Type          : Scan
Aborted       : No
Scan Mode     : Standard
Updates Count : 5

************************* Warnings *************************

************************* Updates *************************
Foxit PDF Editor (32-bit), version 12.1.3.15356
  [+] Available Version        : 2023.3.0.23028
  [+] Size                     : 2,15 GB
  [+] Wow6432                  : Yes
  [+] Portable                 : No
  [+] update_location          : C:\Program Files (x86)\Foxit Software\Foxit PDF Editor\

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
We'll look into this issue soon. Thanks for posting it

**Comment by Tigzy** [comment]
I believe the free version is called 
`Foxit PDF Reader (32 bits)` 
and the paid version
`Foxit PDF Editor (32-bit)`

We'll fix that.

**Comment by 00Eraser00** [comment]
That's true, but as stated above, there are also 2 paid versions, which have the same name but different versioning.
