### ISSUE TITLE
UCheck v5.3.1 Bug - New Text in Filter Button Truncated

### ISSUE THREAD

**Issue by ljmacri** [AdliceSoftware/UCheck#39]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [ ] I am reporting an issue for UCheck BETA

### What happened?

According to the change log for v5.3.1.0 at https://www.adlice.com/docs/ucheck/release-notes/changelog/ one of the changes made in the latest version is "Added filtered count in filter button (installed / updates tabs)".

The text on that filter button is now truncated (see attached image) unless I maximize the size of the UCheck interface so that it fills my entire screen.

![UCheck v5_3_1 Text on Filter Button Truncated 08 Mar 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/e5cf99e6-6c6f-4fbd-948d-63cfad24fed4)

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Fixed in next beta.
