### ISSUE TITLE
StarCraft II wrong version recognized

### ISSUE THREAD

**Issue by 00Eraser00** [AdliceSoftware/UCheck#40]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [ ] I am reporting an issue for UCheck BETA

### What happened?

Hi,

UCheck recognizes the wrong version of StarCraft II and says there is an update available when I'm already on the latest version. It detects version 5.0.12.25579 when in fact the latest version 5.0.12.91115 is installed. 

The uninstallation entry in the registry looks like this:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\StarCraft II]
"DisplayName"="StarCraft II"
"UninstallString"="\"C:\\ProgramData\\Battle.net\\Agent\\Blizzard Uninstaller.exe\" --lang=enUS --uid=s2_engb --displayname=\"StarCraft II\""
"Comments"="StarCraft II"
"Publisher"="Blizzard Entertainment"
"DisplayIcon"="I:\\StarCraft II\\Support\\SC2Switcher.exe"
"InstallLocation"="I:\\StarCraft II"
"InstallSource"="I:\\StarCraft II"
"Contact"="Blizzard Support"
"HelpLink"="http://us.blizzard.com/support/"
"URLInfoAbout"="http://us.blizzard.com/support/"
"URLUpdateInfo"="http://us.blizzard.com/support/"
```

Battle.net says I have the latest version. 
![Screenshot 2024-02-29 220232](https://github.com/AdliceSoftware/UCheck/assets/46270487/033a2c01-8e58-49f0-9ff0-ba91dba802ea)
[Nirsofts UnistallView](https://www.nirsoft.net/utils/uninstall_view.html) lists the correct version too.

It seems you're checking the wrong version property.
![Screenshot 2024-02-29 224411](https://github.com/AdliceSoftware/UCheck/assets/46270487/7ebc39ae-50e9-4be6-8231-c21f824981bb)

```
Sigcheck v2.90 - File version and signature viewer
Copyright (C) 2004-2022 Mark Russinovich
Sysinternals - www.sysinternals.com

i:\starcraft ii\versions\base91115\SC2.exe:
        Verified:        Signed
        Signing date:        20:00 27.09.2023
        Publisher:        Blizzard Entertainment, Inc.
        Company:        Blizzard Entertainment, Inc.
        Description:        StarCraft II
        Product:        StarCraft II (Retail)
        Prod version:        Version 5.0.12.91115
        File version:        5.0.12.91115
        MachineType:        32-bit
        Binary Version:        5.0.12.25579
        Original Name:        StarCraft II.exe
        Internal Name:        StarCraft II
        Copyright:        ? 2010-2023 Blizzard Entertainment, Inc.
        Comments:        n/a
        Entropy:        7.866
```

### ucheck-report

Program       : UCheck
Version       : 5.3.1.0
x64           : Yes
Program Date  : Mar  8 2024
Location      : C:\Program Files\UCheck\UCheck64.exe
Premium       : No
Company       : Adlice Software
Website       : https://www.adlice.com/
Contact       : https://adlice.com/contact/
Website       : https://adlice.com/download/ucheck/
Operating System : Windows 10 (10.0.19045) 64-bit
64-bit OS     : Yes
Startup       : 0
WindowsPE     : No
User          : Jan
User is Admin : Yes
Date          : 2024/03/13 15:03:33
Type          : Scan
Aborted       : No
Scan Mode     : Standard
Updates Count : 5
Arguments     : -nomutex

************************* Warnings *************************

************************* Updates *************************
StarCraft II (64-bit), version 5.0.12.25579
  [+] Available Version        : 5.0.12.91115
  [+] Size                     : 0
  [+] Wow6432                  : No
  [+] Portable                 : No
  [+] update_location          : I:\StarCraft II

************************* Installed *************************

StarCraft II (64 bits), version 5.0.12.25579
  [+] Uninstall           : HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\StarCraft II
  [+] Location            : I:\StarCraft II

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Unfortunately this looks like a very specific version checking, and we're talking about a community version right ?
Whta puzzles me is that the reported version should also be the checked version, even when it's wrong... 
Closing for now, as I see in the db this number is already obsolete now

**Comment by 00Eraser00** [comment]
@Tigzy 
Yes, it's a community version, but it's true for the next version too. Should I open a new issue, or can this one be reopened?
