### ISSUE TITLE
Allow user to specify path to winget.exe

### ISSUE THREAD

**Issue by stevehoek** [AdliceSoftware/UCheck#42]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I checked that the feature I'm requesting is not available in UCheck Beta
- [X] I checked that the feature I'm requesting was not already requested

### Which feature do you want to be added ?

On Windows Server machines, it is possible to install Winget but not using the traditional desktop app installer / windows store mechanism.  This results in a Winget install location that UCheck 5.40 BETA-1 cannot locate.
Also, Winget releases from their Github can be installed in parallel with the Store version and may want to be used with UCheck.

Please add a feature to allow us to specify the location of Winget

For reference, check out WinGetUI which aggregates updates from all sorts of package managers like Winget, Chcolatey, etc.
They allow this to be configured.

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
I'm closing this since now Winget path is dynamically found on the machine.
