### ISSUE TITLE
CRITICAL	[UCheck::GetWingetList] Unable to parse winget output

### ISSUE THREAD

**Issue by stevehoek** [AdliceSoftware/UCheck#44]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [X] I am reporting an issue for UCheck BETA

### What happened?

Using 5.4.0 BETA2 it can no longer parse the Winget output 
Using Winget v1.7.10861

Output of "winget list --disable-interactivity" is attached

[winget-list.txt](https://github.com/AdliceSoftware/UCheck/files/14968997/winget-list.txt)

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by stevehoek** [comment]
I rolled back to BETA1 and it can parse it correctly

**Comment by Tigzy** [comment]
Thanks, could you tell me what the output looks like for "winget upgrade" ?

**Comment by stevehoek** [comment]
Here you go @Tigzy 

[winget-upgrade.txt](https://github.com/AdliceSoftware/UCheck/files/14979192/winget-upgrade.txt)

**Comment by Tigzy** [comment]
Ok so I believe the next BETA should work. thanks

**Comment by stevehoek** [comment]
It is working with BETA3... thanks!
