### ISSUE TITLE
UCheck doesn't find any winget apps on Windows Server 2019

### ISSUE THREAD

**Issue by stevehoek** [AdliceSoftware/UCheck#45]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [X] I am reporting an issue for UCheck BETA

### What happened?

Winget works on Windows Servers (2019, 2022) but has a few known issues.  For one, the UWP call to get the resource strings does not exist on the Server platform, so by default Winget just shows its placeholder label.  For instance, here is Winget's output showing CLI commands:

`WindowsPackageManager
MainCopyrightNotice

ToolDescription

Usage [<Command>] [<Options>]

AvailableCommands
  install    InstallCommandShortDescription
  show       ShowCommandShortDescription
  source     SourceCommandShortDescription
  search     SearchCommandShortDescription
  list       ListCommandShortDescription
  upgrade    UpgradeCommandShortDescription
  uninstall  UninstallCommandShortDescription
  hash       HashCommandShortDescription`

UCheck can't seem to parse the output of "winget list" in this case; I guess it is looking for the actual strings? 

Here is my winget list output from a Server 2019 machine
[winget-list.txt](https://github.com/AdliceSoftware/UCheck/files/14985817/winget-list.txt)

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Could you send me the output of `winget upgrade` command ?
Also, is there any error in the logs ?

**Comment by stevehoek** [comment]
@Tigzy no errors in the logs, just a message saying it found 0 programs.  My system is fully up to date right now so I will send the winget upgrade logs when I get a new update

**Comment by Tigzy** [comment]
Could you try out the latest BETA see if there's something ?

**Comment by stevehoek** [comment]
@Tigzy unfortunately BETA4 actually logs an error

```
2024/04/19 08:59:15:DEBUG	[UCheck::GetWingetList] Getting winget programs list...
2024/04/19 08:59:19:CRITICAL	[UCheck::GetWingetList] Unable to parse winget list output
2024/04/19 08:59:19:DEBUG	[UCheck::GetWingetList] Found 0 winget programs and 0 updates available.

```

**Comment by stevehoek** [comment]
Here is my winget-list and winget-upgrade output

[winget-upgrade.txt](https://github.com/AdliceSoftware/UCheck/files/15099086/winget-upgrade.txt)
[winget-list.txt](https://github.com/AdliceSoftware/UCheck/files/15099087/winget-list.txt)

**Comment by Tigzy** [comment]
I see no problem with parsing those files in the latest changes. Let's see what the main release says.

**Comment by stevehoek** [comment]
Seems to work with the official release of 5.4.0... thanks!
