### ISSUE TITLE
Since 5.4.0.0 - Beta1 the portable version (License: Free) starts to call out to - https://licensing.adlice.com - ending in Error 400 server-side

### ISSUE THREAD

**Issue by RonnyTNL** [AdliceSoftware/UCheck#46]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [X] I am reporting an issue for UCheck BETA

### What happened?

Since 5.4.0.0 - Beta1 the portable version (License: Free) starts to call out to - https://licensing.adlice.com POST /api/v1/index.php?action=getinstances - ending in Error 400 server-side

Is this call supposed to happen? and if yes is there a server-side issue?

### ucheck-report

2024/04/19 10:35:38:DEBUG	[Workers::Register] Registering worker (AdvertNotifs)...
2024/04/19 10:35:39:CRITICAL	[CurlHelper::Post] Error (HTTP:400) on https://licensing.adlice.com/api/v1/index.php?action=getinstances
2024/04/19 10:35:39:CRITICAL	[Licensing::GetActivations] Unable to get response from server
2024/04/19 10:35:39:CRITICAL	[CurlHelper::Post] Error (HTTP:400) on https://licensing.adlice.com/api/v1/index.php?action=getinstances
2024/04/19 10:35:39:CRITICAL	[Licensing::GetActivations] Unable to get response from server
2024/04/19 10:35:39:CRITICAL	[CurlHelper::Post] Error (HTTP:400) on https://licensing.adlice.com/api/v1/index.php?action=getinstances
2024/04/19 10:35:39:CRITICAL	[Licensing::GetActivations] Unable to get response from server

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
It should be fixed in latest stable.
