### ISSUE TITLE
Enable Github Discussions tab

### ISSUE THREAD

**Issue by necros2k7** [AdliceSoftware/UCheck#48]
@Tigzy @CursonMF 
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I checked that the feature I'm requesting is not available in UCheck Beta
- [X] I checked that the feature I'm requesting was not already requested

### Which feature do you want to be added ?

Enable Github Discussions tab

### Don't forget to vote !

- [x] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Hey, I'm not sure what you mean by discussion tab ? You can discuss directly in the comment section

**Comment by Tigzy** [comment]
Nvm, I found.
