### ISSUE TITLE
Multiple Microsoft Apps Change to "Unsupported" When Winget is Disabled in UCheck v5.4.0.0

### ISSUE THREAD

**Issue by ljmacri** [AdliceSoftware/UCheck#50]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [ ] I am reporting an issue for UCheck BETA

### What happened?

I am currently running the latest stable release of UCheck v5.4.0.0 (rel. 07-May-2024) on my Win 10 machine from a removable USB stick. 

When Winget is turned OFF at History & Settings | Scan Settings | Winget multiple Microsoft applications previously classified as "Winget" apps are incorrectly re-classified as "Unsupported" instead of "Community".

### ucheck-report

If **Winget is ON** at History & Settings | Scan Settings | Winget the Installed tab lists **33 supported applications** and UCheck finds **5 available updates** ...

[UCheck v5_4_0_0 Scan Log Winget ON 17 May 2024.txt](https://github.com/AdliceSoftware/UCheck/files/15354704/UCheck.v5_4_0_0.Scan.Log.Winget.ON.17.May.2024.txt)
[UCheck v5_4_0_0 Debug Log Winget ON 17 May 2024.txt](https://github.com/AdliceSoftware/UCheck/files/15354705/UCheck.v5_4_0_0.Debug.Log.Winget.ON.17.May.2024.txt)

![UCheck v5_4_0_0 Winget Scan ON 36 Installed M to W 17 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/52b27c1f-7915-4f27-81c4-e1420cce99a8)

![UCheck v5_4_0_0 Winget Scan ON Updates 5 Updates Detected 17 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/b618dd3a-d854-4575-9233-3db0d415e5fc)

... but if I **Winget is OFF** at History & Settings | Scan Settings | Winget the Installed tab only lists **25 supported applications** and UCheck only finds **2 available updates**. 

It appears that I have **8 applications** (Microsoft Edge Update, all Microsoft .NET Runtimes and all Microsoft Visual C++ Redistributables) that now disappear when Winget is turned OFF because they are incorrectly (???) re-classified as "Unsupported" when they should be re-classified  as "Community".

**IMPORTANT NOTE**: My outdated **Windows PC Health Check** app changes from a "Winget" app to a "Community" app as expected when Winget is turned OFF. 

[UCheck v5_4_0_0 Scan Log Winget OFF 17 May 2024.txt](https://github.com/AdliceSoftware/UCheck/files/15354757/UCheck.v5_4_0_0.Scan.Log.Winget.OFF.17.May.2024.txt)
[UCheck v5_4_0_0 Debug Log Winget OFF 17 May 2024.txt](https://github.com/AdliceSoftware/UCheck/files/15354759/UCheck.v5_4_0_0.Debug.Log.Winget.OFF.17.May.2024.txt)

![UCheck v5_4_0_0 Winget Scan OFF 25 Installed M to W NW 17 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/684ba6be-59a0-4270-abac-d289d7d5ca8d)

![UCheck v5_4_0_0 Winget Scan OFF Updates 2 Updates Detected 17 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/fd8990bf-f1eb-43cd-942b-da2dc89fadf7)

I'm not certain, however, that Adlice would consider this Winget behaviour to be an actual bug for all 8 applications since I can't find an old screenshot from a previous version of UCheck that proves that my Microsoft .NET Core Runtime v3.x and Microsoft Windows Desktop Runtime v8.x used to be classified as "Community" apps before Winget support was added to UCheck v5.4.0.0.  

FYI, I don't really care if UCheck supports Microsoft Edge Update or the Microsoft Visual C++ Redistributables - I'll likely create exclusions for the Visual C++ Redistributables apps because I don't want these apps updated to the latest available versions in case this breaks some of my older, unsupported software like Microsoft Money Plus.

----------------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.4291 * Firefox v126.0.0 * Microsoft Defender v4.18.24040.4-1.1.24040.1 * Malwarebytes Premium v 5.1.4.112-1.0.1233 * Macrium Reflect Free v8.0.7783 * QuickInstaller (Preview) v0.3.8859.20616 * UCheck v5.4.0.0 (stable)

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Hi,
Yes VC++ are now unsupported from Community because it had too many FP issues.
We have added a global exclusion for them
