### ISSUE TITLE
Ucheck 5.4.0 now flags all previous versions of the Windows .NET Desktop Runtime as needing to update to a v9 beta

### ISSUE THREAD

**Issue by HayesE** [AdliceSoftware/UCheck#51]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [ ] I am reporting an issue for UCheck BETA

### What happened?

Each .NET Desktop Runtime numbered version is a separately maintained build, from versions 6, 7, 8, and now v9. Each all receive patch Tuesday monthly updates. Ucheck now ham-fistedly flags any 6, 7, or v8 version of the .NET Desktop runtime as needing to be replaced with the version 9 preview still in beta.

### ucheck-report

![ucheck](https://github.com/AdliceSoftware/UCheck/assets/121079365/660ec1cd-21a6-49cb-8f4f-dbceb15d7cb9)

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Should be fixed in 5.5 BETA
