### ISSUE TITLE
Some fonts are too small

### ISSUE THREAD

**Issue by Tigzy** [AdliceSoftware/UCheck#6]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [ ] I am reporting an issue for UCheck BETA

### What happened?

Some fonts across UCheck are too tiny to read.
Let's improve that.

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [ ] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by jascoet-mwb** [comment]
Should be adressed with version `5.0.6`

**Comment by Tigzy** [comment]
Should be adressed with version `5.0.6`
