### ISSUE TITLE
[Community] Portable apps support

### ISSUE THREAD

**Issue by Tigzy** [AdliceSoftware/UCheck#7]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I checked that the feature I'm requesting is not available in UCheck Beta
- [X] I checked that the feature I'm requesting was not already requested

### Which feature do you want to be added ?

Support portable apps in Community database
- [X] Custom locations as a setting
- [X] Separate views in "Installed" tab
- [X] Filter out uninteresting files
- [ ] Send list to community database
- [ ] Get manifest from community database 

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Implemented in 5.1

**Comment by necros2k7** [comment]
How to set custom locations path to scan in CLI version (if supported)?
