### ISSUE TITLE
Portable Apps With "Uninstaller" in Program Name Not Detected by UCheck BETA v5.0.6.0

### ISSUE THREAD

**Issue by ljmacri** [AdliceSoftware/UCheck#9]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [X] I am reporting an issue for UCheck BETA

### What happened?

UCheck BETA v5.0.6.0 (rel. 23-Nov-2023) is unable to detect executables for Portable apps that have a program name that includes "Uninstaller" (e.g., Revo Uninstaller Free Portable, Geek Uninstaller Portable, etc.) unless the executable is renamed to include the string "portable".

To reproduce the issue:

1. Download Geek Uninstaller Portable (geek.zip) from https://geekuninstaller.com/download and unzip the file on a removable USB stick in it's own folder (e.g. E:\Portable\Geek Uninstaller 1_5_2).  This will unzip the **geek.exe** executable (see file properties in image A).
2. Ensure this folder (e.g., E:\Portable) is added as a custom location in UCheck at History & Settings | Custom Locations.
3. Launch UCheck, run a scan from the main dashboard, and go to Installed | Portable. The geek.exe executable is not detected (see image B) and the UCheck debug log at C:\ProgramData\UCheck\Debug\UCheck_debug.log states "_App is uninteresting, filtering: E:\Portable\Geek Uninstaller 1_5_2\geek.exe_"
4. Close UCheck. Use File Explorer to rename the geek.exe file at E:\Portable\Geek Uninstaller 1_5_2 to **geek_portable.exe**.
5. Re-launch UCheck, run a scan from the main dashboard, and go to Installed | Portable. The renamed geek_portable.exe is now detected (see image C).

![A - Win 10 Pro v22H2 File Explorer Geek Uninstaller Portable v1_5_2 File Properties 30 Nov 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/c55e8774-23bf-4e67-ae21-b584177fd6e1)

![B - UCheck BETA v5_0_6_0 Geek Uninstaller Portable v1_5_2 geek_exe Not Detected 30 Nov 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/f913f055-161d-4a97-9612-b383ca6c8bdd)

![C - UCheck BETA v5_0_6_0 Geek Uninstaller Portable v1_5_2 Renamed geek_portable_exe Detected 30 Nov 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/8db6b66c-9bde-4cb3-a91e-6ca39a71f454)

### ucheck-report

From my attached 30-Nov-2023 debug log at C:\ProgramData\UCheck\Debug\UCheck_debug.log when the executable has its original name **geek.exe** assigned by the developer:

2023/11/30 08:02:43:DEBUG	[UCheck::SearchWellKnownLocation] Found app: E:\Portable\Geek Uninstaller 1_5_2\geek.exe
2023/11/30 08:02:43:DEBUG	[UCheck::ShouldFilter] Internal name setup found: E:\Portable\Geek Uninstaller 1_5_2\geek.exe
2023/11/30 08:02:43:DEBUG	[UCheck::SearchWellKnownLocation] **App is uninteresting**, filtering: E:\Portable\Geek Uninstaller 1_5_2\geek.exe

[UCheck_debug.log](https://github.com/AdliceSoftware/UCheck/files/13514865/UCheck_debug.log)

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [x] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Yes, and this is expected as we want to filter out all the uninstall.exe / uninstaller for portable apps. 
The workaround for now is to rename your executable with something like `geek-portable.exe`
Closing as won't fix.
